### ISSUE TITLE
Getting UserTokenRequired error when trying to download image

### ISSUE THREAD

**Issue by iraszl** [gettyimages/gettyimages-api_ruby#12]
Thanks for this nice gem!

I'm able to do searches like this:
`search_results = apiClient.search_images().with_phrase("ostrich").with_fields(["artist", "id", "title"]).with_exclude_nudity("true").with_page(2).with_page_size(5).execute()`

But when trying to get the URL of an image I get an error:
`result = apiClient.download_images().with_id("185235511").execute()`

Error:
`HTTP RESPONSE: {"ErrorCode"=>"UserTokenRequired", "ErrorMessage"=>"Security token must contain a user."}`

The documentation of this gem doesn't mention a UserToken. Do I need anything besides the listed `api_key` and `api_secret` or what am I missing?

**Comment by mapitman** [comment]
It depends on how we have setup your API key at the Getty Images side of things. It sounds like in your case, you would need the username and password of a Getty Images user with an active agreement. There is an overload when creating the client that accepts those values.
https://github.com/gettyimages/gettyimages-api_ruby/blob/master/lib/ApiClient.rb#L17

I'm afraid our examples don't cover that case.

**Comment by mapitman** [comment]
If you do not need to download a full size image, you may be able to use one of the display sizes (thumb, preview or comp):

```
search_results = apiClient.search_images().with_phrase("ostrich")
.with_fields(["artist", "id", "title", "thumb", "preview", "comp"])
.with_exclude_nudity("true").with_page(2).with_page_size(5).execute()
```

**Comment by mapitman** [comment]
Based on an internal email, I see now that what you are really looking for is the `referral_destinations` field. If you add that to the `.with_fields()` method call, you will receive a list of links to the asset detail pages for all of the assets in your search results.

**Comment by iraszl** [comment]
Thank you so much! This answered my question!
