### ISSUE TITLE
Is it possible to get larger non-watermarked thumbnails?

### ISSUE THREAD

**Issue by iraszl** [gettyimages/gettyimages-api_ruby#13]
I'm using below query to get search results and I get 3 display sizes:

- comp (watermarked)
- preview (watermarked)
- thumb (not watermarked)

```images_search_result = apiClient.search_images().with_phrase(keyword).with_fields(["collection_name", "artist", "id", "title", "thumb", "preview", "comp", "referral_destinations"]).with_exclude_nudity("true").with_page(1).with_page_size(10).execute()```

Is it possible to get a larger size thumb than the max 192px wide provided by this query? This low-res size doesn't look great on the site I'm building.

Example of low res: https://media.istockphoto.com/videos/baby-wearing-yellow-bathrobe-duck-on-parents-bed-after-bath-video-id1288147432?b=1&k=20&m=1288147432&s=192x192&h=Wbp4NY5ZE3cMSdIYHbMEe_GvnXCxuxfjJyfu-_sn-R8=

I'm assuming it's possible up to 640px wide, because you can see it being used here: https://www.adsoftheworld.com/?terms=fish&created=all&country=All&medium=All&industry=All

Example of high-res: https://media.istockphoto.com/videos/school-of-fish-video-id474275548?b=1&k=20&m=474275548&s=640x640&h=AuAbIvVs4oML-GVr16DVW65v4GJrMnp14lwIT380Bxo=

Thank you!

**Comment by mapitman** [comment]
Please get in touch with your affiliate contact. They can make that change for you.

**Comment by iraszl** [comment]
Thank you!
