### ISSUE TITLE
Why this particular build / install process?

### ISSUE THREAD

**Issue by tomav** [gettyimages/gettyimages-api_ruby#3]
Hi guys,

I was wondering why:
1. the gem is not available on rubygems
2. this source code is not using the common format to be installed with `gem 'gettyimages', :github => 'gettyimages/gettyimages-api_ruby'` 

This doesn't help to use and improved this gem.
Of course, this is just a question, not a critic.

Thank you.

**Comment by mapitman** [comment]
Hello, we are in the process of renaming the SDK and doing some updates. 

1. The gem can be found here: https://rubygems.org/gems/ConnectSDK.
1. I'm not the one who wrote the Ruby SDK so I'm not sure why it can't be installed that way. 

There should be some work on our SDKs coming in the next few weeks. We'll look at the install issue during that time.

**Comment by tomav** [comment]
Perfect. Thank you.
