### ISSUE TITLE
cannot load such file -- ConnectSdk

### ISSUE THREAD

**Issue by crunchycarrot** [gettyimages/gettyimages-api_ruby#4]
class FrontendController < ApplicationController
  def index
		require "ConnectSdk"

		api_key = "3fgmytrtrh4scjba65r2e47n"
		api_secret = "xxxxxxxxx"

Can you help?

**Comment by Sarukod** [comment]
Hi,

Don't know if you are having an issue but there is an available ruby gem for the SDK - https://rubygems.org/gems/ConnectSDK. 

If you use the code snippet from the usage section of the read me file on the repo - https://github.com/gettyimages/gettyimages-api_ruby, it should produce search results.

require "ConnectSdk"

api_key = "Connect API Key"
api_secret = "Connect API Secret"

# create instance of the Connect SDK
connectSdk = ConnectSdk.new(api_key, api_secret)
search_results = connectSdk
    .search().images()
    .with_phrase("gorilla")
    .with_page(2)
    .with_page_size(5)
    .execute()

search_results["images"].each do | image |
    puts "Id: #{image["id"]} Title: #{image["title"]}" 
end
