### ISSUE TITLE
bug when passing frozen string parameter to search images api

### ISSUE THREAD

**Issue by GuyFlenner** [gettyimages/gettyimages-api_ruby#8]
Hello @ChrisSimmons , @mapitman 
We would love to use this gem for our site integration with Getty Images.
There is a bug when we pass frozen string parameters to `search_images` API, e.g:

```
# frozen_string_literal: true
class RetrieveImages
  SEARCH_FIELD = 'test'

  def search
    ApiClient.new(key, secret).search_images.with_phrase(SEARCH_FIELD)
  end
end
```

`error => FrozenError: can't modify frozen String`

after debugging the gem, we found the place of error: (SearchImages.rb) line 17 or line 22
it's not possible to do `value.downcase!` on frozen string

```
...
QUERY_PARAMS_NAMES.each do |key|
    define_method :"with_#{key}" do |value = true| 
			if value.is_a?(Array)
				value = value.join(",")
				if (!key.include? "id") && (!key.include? "orientations")
					value.downcase!
				end	
    			build_query_params(key, value)
			else
				if (!key.include? "id") && (!key.include? "orientations") && (value.is_a?(String))
					value.downcase!
				end	
...
```

is it possible to change it to: `value = value.downcase` ?
It seems to work and all test under unit_tests/SearchImagesTests.rb are passing
I couldn't create pull request because I don't have permissions

**Comment by mapitman** [comment]
This looks like a good change to make. Can you give more info on what's happening when you try to make a pull request?

**Comment by ChrisSimmons** [comment]
Closing this given the age.  @GuyFlenner please re-open if you have feedback on the above.
